### ISSUE TITLE
travis encrypt not working

### ISSUE THREAD

**Issue by shawnps** [travis-ci/travis-deploy#5]
Could be user error:

``` Shell
➜  ~  ruby --version
ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-darwin11.4.2]
➜  ~  gem install travis
Fetching: travis-0.0.8.gem (100%)
Successfully installed travis-0.0.8
1 gem installed
Installing ri documentation for travis-0.0.8...
Installing RDoc documentation for travis-0.0.8...
➜  ~  travis encrypt gengo/gengo-python FOO=bar 

About to encrypt 'FOO=bar' for 'gengo/gengo-python'

dyld: lazy symbol binding failed: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/shawn/.rvm/gems/ruby-1.9.3-p286/gems/yajl-ruby-0.8.3/ext/yajl/yajl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _yajl_set_static_value
  Referenced from: /Users/shawn/.rvm/gems/ruby-1.9.3-p286/gems/yajl-ruby-0.8.3/ext/yajl/yajl.bundle
  Expected in: flat namespace

[1]    5790 trace trap  travis encrypt gengo/gengo-python 
```

**Comment by shawnps** [comment]
It worked after I installed yajl-ruby.

**Comment by sarahhodne** [comment]
I couldn't reproduce this:

```
[hodne2@gelib-057-35 ~]$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]
[hodne2@gelib-057-35 ~]$ gem install travis
/home/hodne2/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/yaml.rb:56:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
Fetching: thor-0.16.0.gem (100%)
Fetching: multi_json-1.3.7.gem (100%)
Fetching: travis-0.0.8.gem (100%)
Successfully installed thor-0.16.0
Successfully installed multi_json-1.3.7
Successfully installed travis-0.0.8
3 gems installed
Installing ri documentation for thor-0.16.0...
Installing ri documentation for multi_json-1.3.7...
Installing ri documentation for travis-0.0.8...
Installing RDoc documentation for thor-0.16.0...
Installing RDoc documentation for multi_json-1.3.7...
Installing RDoc documentation for travis-0.0.8...
[hodne2@gelib-057-35 ~]$ travis encrypt gengo/gengo-python FOO=bar
/home/hodne2/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/yaml.rb:56:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.

About to encrypt 'FOO=bar' for 'gengo/gengo-python'

Please add the following to your .travis.yml file:

  secure: "q6AmHeR74waFFcEeGMGVjBAyUNE0MFlFfVfM5uPQ2xfPZUqk7hy5Zj+bHbrr\nQSGTzhNabqeuy2s5mEygTjBbE1kR4iixrsJ/n5KYcIClO3AqyRhGNEyAt6+D\nDK9NaR/9oKJSBp0e6pfWipziWRoFnN2MpQGZcuaOYeJTySECZFk="
```

**Comment by drogus** [comment]
It looks like ruby version was upgraded but libs were not.
